### ISSUE TITLE
Subheading Correction : Freshman Undergraduate

### ISSUE THREAD

**Issue by vatsalyatandon** [aryanc403/Resume#1]
Junior Undergraduate is meant for 3rd year students. Year wise break-up follows:-

Freshman -> 1st year
Sophomore -> 2nd year
Junior -> 3rd year
Senior -> 4th year

**Comment by aryanc403** [comment]
I'm seeing this issue now. It will be fixed soon.

**Comment by aryanc403** [comment]
Resolved now.
